server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB


logging:
  level:
    root: info
    com.hjf.music.dao: debug


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis-plus/mapper/*.xml


